config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  get 'welcome/gallery'
  get 'welcome/about_us'
  get 'welcome/mission'
  get 'welcome/chairman_message'
  get 'welcome/principal_message'
  get 'welcome/mandatory_public_disclosure'
  get 'welcome/academic_calender'
  get 'welcome/three_year_results'
  get 'welcome/book_list'
  get 'welcome/committee'
  get 'welcome/committees'
  get 'welcome/pta'
  get 'welcome/faculty'
  get 'welcome/oasis_updated'
  get 'welcome/result_date_sheet'
  get 'welcome/admission_procedure'
  get 'welcome/public_disclosure'
  get 'welcome/deo_certificate'
  get 'welcome/prospectus'
  get 'welcome/noc'
  get 'welcome/recognition'
  get 'welcome/land_certificate'
  get 'welcome/society_certificate'
  get 'welcome/water_certificate'
  get 'welcome/affiliation_letter'
  get 'welcome/fire_safety'
  get 'welcome/building_safety_certificate'
  get 'welcome/transport_safety'

  get 'welcome/fee_stracture'
  get 'welcome/norms_of_fixing_fee'
  get 'welcome/student_strength'
  get 'welcome/tc_entries'
  get 'welcome/activities_compatitions'
  get 'welcome/school_building'
  get 'welcome/transport_facilities'
  get 'welcome/class_room'
  get 'welcome/infirmary'
  get 'welcome/library'
  get 'welcome/laboratories'
  get 'welcome/photos'
  get 'welcome/videos'
  get 'welcome/contact_us'
  get 'welcome/feedback'

  resources :tc_entries do 
    collection do 
      get :tc
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  CONTENT_TYPES = [
    ["SLIDER 1", "slider_one"],
    ["SLIDER 2", "slider_two"],
    ["SLIDER 3", "slider_three"],
    ["Activities", "activities"],
    ["Infrastructure", "infrastructure"],
    ["Facilities", "facilities"],
    ["Welcome Section", "welcome_section"],
    ["Salient Features", "salient_features"],
    ["Teacher Count", "teacher_count"],
    ["Student Count", "student_count"],
    ["Room Count", "room_count"],
    ["President Message", "president_message"],
    ["Director Message", "director_message"],
    ["Principal's Message", "principal_message"],
    ["About Us Page", "about_us"]
  ]
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :file, DocumentUploader
  DOCUMENT_TYPES = [
    ["Fee structure", "fee_structure"],
    ["Land Certificate", "land_certificate"],
    ["OASIS Document", "oasis"],
    ["Affiliation letter", "affiliation_letter"],
    ["Academic Calendar", "academic_calendar"],
    ["Society/Trust Registration Certificate", "society_registration_certificate"],
    ["No Objection Certificate", "noc"],
    ["Staff Details", "staff_details"],
    ["Recognition Certificate", "recognition_certificate"],
    ["Building safety certificate", "building_safety_certificate"],
    ["Fire safety certificate", "fire_safety_certificate"],
    ["DEO Certificate for Affiliation", "deo_certificate"],
    ["Public Disclosure", "public_disclosure"],
    ["Water sanitation certificate", "water_sanitation_certificate"],
    ["Academic calendar", "academic_calendar"],
    ["Book List with Declaration", "book_list"],
    ["Last three year results", "last_three_year_results"],
    ["Official of Different Committee of the School", "committee"],
    ["School committees stracture", "committee_stracture"],
    ["Norms of fixing fee", "norms_of_fixing_fee"],
    ["PROSPECTUS", "prospectus"],
    ["Student Details", "student_details"]
  ]

  validates :name, presence: true
  validates :file, presence: true
end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
  mount_uploader :image, GalleryImageUploader

  SECTION = [
    ["SLIDER", "slider"],
    ["Banner", "banner"],
    ["About Section", "about_section"],
    ["Photo Gallery", "photo_gallery"],
    ["Principal Photo", "principal_photo"],
    ["Director Photo", "director_photo"],
    ["Manager Photo", "manager_photo"],
    ["Library Photo", "library_photo"],
    ["Laboratory Photo", "laboratory_photo"]
  ]

  scope :active, -> { where(is_active: true) }

  validates :image, presence: true
end

app/models/gallery_video.rb
class GalleryVideo < ApplicationRecord
  mount_uploader :video, GalleryVideoUploader

  validates :title, presence: true
  validates :video, presence: true
end

app/models/tc_entry.rb
class TcEntry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token
	before_action :url_options

	def url_options
    super
    @_url_options.dup.tap do |options|
      options[:protocol] = Rails.env.production? ? "http://" : "http://"
      options.freeze
    end
  end
end

app/controllers/tc_entries_controller.rb
class TcEntriesController < ApplicationController
  layout :resolve_layout

  def index
    @tc_entries = TcEntry.all
    if params[:query].present?
      @tc_entries = TcEntry.where("concat_ws(' ' , LOWER(tc_number), LOWER(student_name), LOWER(father_name), LOWER(mother_name)) LIKE ?", "%#{params[:query].downcase}%")
    end

  end

  def tc
    @tc_entry = TcEntry.first
    respond_to do |format|
      format.html
    end
  end

  def show
    @tc_entry = TcEntry.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  private

  def resolve_layout
    case action_name
    when "show"
      "pdf"
    else
      "application"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @banner_image = GalleryImage.active.where(section: 'banner').last
    @slider_images = GalleryImage.active.where(section: 'slider')
    @about_image = GalleryImage.active.where(section: 'about_section').last
    @photos = GalleryImage.active.where(section: 'photo_gallery')
    @slider_one = Content.where(content_type: 'slider_one').last
    @slider_two = Content.where(content_type: 'slider_two').last
    @slider_three = Content.where(content_type: 'slider_three').last
    @activity = Content.where(content_type: 'activities').last
    @infrastructure = Content.where(content_type: 'infrastructure').last
    @facilities = Content.where(content_type: 'facilities').last
    @welcome_section = Content.where(content_type: 'welcome_section').last
    @salient_features = Content.where(content_type: 'salient_features').last
    @teacher_count = Content.where(content_type: 'teacher_count').last
    @student_count = Content.where(content_type: 'student_count').last
    @room_count = Content.where(content_type: 'room_count').last
    @president_message = Content.where(content_type: 'president_message').last
    @director_message = Content.where(content_type: 'director_message').last
    @principal_message = Content.where(content_type: 'principal_message').last
    @principal_photo = GalleryImage.active.where(section: 'principal_photo').last
    @manager_photo = GalleryImage.active.where(section: 'manager_photo').last
    @director_photo = GalleryImage.active.where(section: 'director_photo').last
  end

  def gallery
  	@photos = GalleryImage.active.where(section: 'photo_gallery')
  end
  
  def about_us
  	@about_us = Content.where(content_type: 'about_us').last
  end

  def mission
  	
  end
  def chairman_message
  	@president_message = Content.where(content_type: 'president_message').last
  end

  def principal_message
  	@principal_message = Content.where(content_type: 'principal_message').last
  end

  def director
    @director_message = Content.where(content_type: 'director_message').last
  end

  def mandatory_public_disclosure
  end

  def contact
    
  end

  def academic_calendar
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tc_entries_helper.rb
module TcEntriesHelper
	def time_format time
		time.strftime("%d/%m/%Y") 
	end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="top_footer_info__block ptb-20">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="single_info__block">
            <i class="fa fa-phone"></i>
            <h4>+91- 9793757651 <span>Monday-Saturday, 8am-4pm</span></h4>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="single_info__block">
            <i class="fa fa-envelope-o"></i>
            <h4>sdskidsips@gmail.com <span>Monday-Saturday, 8am-4pm</span></h4>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="single_info__block">
            <i class="fa fa-clock-o"></i>
            <h4>School Timing <span>8AM - 2pm</span></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main_footer__block pb-0 pt-60">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="footer_box__block">
            <h4>Useful links</h4>
            <%= render 'layouts/side_bar' %>
          </div>
        </div>
        <div class="col-md-9">
          <div>
            <h4>How to Reach Us</h4>
            <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=%SDSK International Public%20School%2C%Jhinjhak%2C%20UP%20%2C%20India&amp;t=m&amp;z=10&amp;output=embed&amp;iwloc=near" title=" Shri Dhunnu Singh Kids International Public School , Jhinjhak, UP , India" aria-label="SDSK International Public School, Jhinjhak, UP , India" width="95%" height="400" frameborder="0" style="border:0; padding-bottom:20px" allowfullscreen></iframe>
            
          </div>
        </div>
      </div>
      <div class="copyriight_block ptb-20 mt-20">
        <div class="row">
          <div class="col-sm-12">
            <p style="text-align:center; font-size:12px">© COPYRIGHT <%= Date.today.year %> SDSK International Public School | ALL RIGHTS RESERVED | DEVELOPED BY <a href="https://www.linkedin.com/in/vaibhav-dwivedi-8a7287185" target="_blank">VAIBHAV DWIVEDI</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<style type="text/css">
  .main_footer__block{
    background-image: url(<%= asset_path 'footer_bg.jpg' %>);
    background-size: cover;
    background-position:top center;
    background-repeat: no-repeat;
    position: relative;
    z-index: 1;
    color: #fff;
  }
  .footer_box__block li::after{
    top: 15px;
  }
</style>

app/views/layouts/_header.html.erb
<header class="header__block">
  <div class="top-part__block ptb-15">
    <div class="container">
        <div class="row">
            <div class="col-sm-7">
                <p style="color: #fff;">Welcome to SDSK International Public School</p>
            </div>
            <div class="col-sm-5">
                <div class="social-link__block text-right">
                    <a href="https://www.facebook.com/RSEducationalSociety"><i class="fa fa-facebook" target="_blank"></i></a>
                    <a href="https://twitter.com/AwsEtawah"><i class="fa fa-twitter"></i></a>
                    <a href="https://www.instagram.com/p/Ca022zRoSu5" target="_blank"><i class="fa fa-instagram"></i></a>
                    <a href="https://www.youtube.com/watch?v=-tr4KrrguY8" target="_blank"><i class="fa fa-youtube"></i></a>
                </div>
            </div>
        </div>
    </div>
    </div>
  <div class="middel-part__block ptb-20">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="logo">
            <a href="#">
              <%= image_tag('logo.jpg', alt:"Logo", style: "width:95px;") %>
            </a>
          </div>
        </div>
        <div class="col-md-8">
          <div class="top-info__block text-right">
            <ul>
              <li>
                <i class="fa fa-map-marker"></i>
                <p>Thakur Harbansh Chowk Uttar Pradesh, Jhinjhak<br />Kanpur (U.P.) 209302 </p>
              </li>
              <li>
                <i class="fa fa-phone"></i>
                <p> +91- 9519015603 <br />""</p>
              </li>
              <li>
                <i class="fa fa-clock-o"></i>
                <p>School Timing <span>8AM - 4PM</span></p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navgation__block stricky-header__top">
    <div class="">
      <div class="row">
        <div class="col-md-12">
          <div class="main-menu__block">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand visible-xs" href="#">
              <img src="/assets/logo.png" alt="">
              </a>
            </div>
            <!--===Navigation===-->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav mobile-menu">
                <li>
                  <a href="<%= root_path %>">Home</a> <span class="submenu-button"></span>                                        
                </li>
                <li>
                  <a href="javascript:avoid(0);">About us</a> <span class="submenu-button"></span>
                  <ul class="dropdown-menu">
                    <li> <a href="<%= welcome_about_us_path %>">Know SDSK International Public School</a> </li>
                    <li> <a href="<%= welcome_mission_path %>">Mission/Vision</a> </li>
                    <li> <a href="<%= welcome_chairman_message_path %>">Chairman's Message</a> </li>
                    <li> <a href="<%= welcome_principal_message_path %>">Principal's Message</a> </li>
                  </ul>
                </li>
                <li>
                  <a href="javascript:avoid(0);">Achievements</a> <span class="submenu-button"></span>
                  <!--<ul class="dropdown-menu">
                    <li> <a href="#">Admission Procedure</a> </li>
                    <li> <a href="#">Fee Structure</a> </li>
                    <li> <a href="#">Online Admission</a> </li>
                    </ul>-->
                </li>
                <li>
                  <a href="javascript:avoid(0);">Academics</a> <span class="submenu-button"></span>
                  <ul class="dropdown-menu">
                    <li> <a href="<%= welcome_fee_stracture_path %>">Fee Structure</a> </li>
                    <li><a href="#" target="_blank">Syllabus</a></li>
                    <li><a href="#" target="_blank">DateSheet</a></li>
                    <li><a href="#">Teaching Staff</a></li>
                    <li><a href="#">Result Class X<sup>th</sup></a></li>
                    <!-- <li><a href="<%#= tc_entries_path %>" target="_blank">AWS TC Data</a></li> -->
                  </ul>
                </li>
                <li>
                  <a href="#">Facilities</a> <span class="submenu-button"></span>
                </li>
                <li>
                  <a href="javascript:avoid(0);">Gallery</a> <span class="submenu-button"></span>
                  <ul class="dropdown-menu">
                    <li> <a href="<%= welcome_gallery_path %>">Photo Gallery</a> </li>
                    <li> <a href="#">Video Gallery</a> </li>
                    <li> <a href="#">Media Gallery</a> </li>
                  </ul>
                </li>
                <li>
                  <a href="#" target="_blank">Prospectus</a> <span class="submenu-button"></span>
                </li>
                <li><a class="" href="<%= welcome_mandatory_public_disclosure_path %>">Mandatory Public Disclosure</a></li>
                <li><a class="" href="<%= welcome_contact_us_path %>">Contact Us</a></li>
                <li><a class="" href="http://www.sdskidsinternational.in/admin/login" target="_blank">Admin Login</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_side_bar.html.erb
<div class="tab-title">
 	<ul class="clearfix">
    <li>
      <a href="<%= welcome_about_us_path %>" class="active">About Us</a>
    </li>
    <li>
      <a href="javascript:avoid(0);">Achievements</a>
    </li>
    <li>
      <a href="javascript:avoid(0);">Academics</a>
    </li>
    <li>
      <a href="javascript:avoid(0);">Facilities</a>
    </li>
    <li>
      <a href="<%= welcome_about_us_path %>">Gallery</a>
    </li>
    <li>
      <a href="<%= welcome_prospectus_path %>" target="_blank">Prospectus</a>
    </li>
  </ul>
</div>
<style type="text/css">
	ul{
		list-style-type: none !important;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SDSK International Public School</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" />
    <script src="https://cdn.ckeditor.com/4.18.0/standard/ckeditor.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/23.1.0/classic/ckeditor.js"></script>

  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AWS ETAWAH</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'pdf', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'pdf', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" />

  </head>

  <body>
    <div class="wrapper">
      <%#= render 'layouts/header' %>
      <%= yield %>
      <%#= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/tc_entries/index.html.erb
<section class="inner-intro about-img light-color overlay-before parallax-background">
  <div class="container">
    <div class="row title">
    </div>
  </div>
</section>
<div id="about-section" class="padding pt-xs-60">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="heading-box pb-30">
          <center><h2><span></span> Students' TC Data</h2></center>
        </div>
      </div>
    </div>
    <div class="row">
    	<div class="col-sm-12 pb-xs-30">
				<%= form_tag tc_entries_path, method: :get do %>
				  <label><h3>Search By TC No., Student Name, Father Name, Mother Name :</h3></label><br>
				  <div class="row">
				  	<div class="col-sm-10">
				  		<%= text_field_tag :'query', nil, class: "form-control" %><br>
				  	</div>
				  	<div class="col-sm-2">
				  		<%= submit_tag "Search", class: "btn btn-primary pull-right" %>
				  	</div>
				<% end %>
				<br><br>
				<br><br>
				<table class="table table-bordered">
				  <thead>
				    <tr>
				      <th scope="col">#</th>
				      <th scope="col">TC No.</th>
				      <th scope="col">Student Name</th>
				      <th scope="col">Father Name</th>
				      <th scope="col">Mother Name</th>
				      <th scope="col">Actions</th>
				    </tr>
				  </thead>
					<tbody>
				  	<% if @tc_entries.present? %>
					    <% @tc_entries.each_with_index do |tc_entry, index|%>
					      <tr>
					        <th scope="row"><%= index + 1 %></th>
					        <td><%= tc_entry.tc_number %></td>
					        <td><%= tc_entry.student_name %></td>
					        <td><%= tc_entry.father_name %></td>
					        <td><%= tc_entry.mother_name %></td>
					        <td><%= link_to "Print", tc_entry_path(tc_entry), target: "_blank"%></td>
					      </tr>
					    <% end %>
					 	<% else %>
					 		<tr>
					 			<td colspan="5"><center><h3>No TC present in system with this criteria. Please click <a href="<%= tc_entries_path %>">here</a> to go back to TC PAGE.</h3></center></td>
					 		</tr>
					</tbody>
					 <% end %>
				</table>
			</div>
		</div>
	</div>
</div>
<style type="text/css">
	.about-img{
    background: url("<%= asset_path('about1.jpg') %>") 0 20% no-repeat;
    -webkit-background-size: cover;
    background-size: cover;
  }
	table{
		border: 1px solid #ccc !important;
	}
	.table > thead > tr > th{
		color: #3a3434 !important;
	}
	.table a{
		color: #3a3434 !important;
	}
</style>

app/views/welcome/building_safety_certificate.html.erb
<section class="inner-intro about-img light-color overlay-before parallax-background">
  <div class="container">
    <div class="row title">
    </div>
  </div>
</section>
<section class="padding ptb-xs-60">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="tab-content">
          <div class="row">
            <div class="col-sm-12">
              <div class="heading-box pb-30">
                <center><h2><span>Building Safety</span> Certificate</h2></center>
              </div>
              <div>
                <% @document = Document.find_by(name: "building_safety_certificate", is_active: true) %>
                <% if @document && @document.file.url %>
                  <iframe id="fred" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="<%= asset_path(@document.file.url) %>" frameborder="1" scrolling="auto" height="700" width="100%" ></iframe>
                  </object>
                <% else %>
                  <iframe id="fred" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="<%= asset_path("BUILDING_SAFETY.pdf") %>" frameborder="1" scrolling="auto" height="700" width="100%" ></iframe>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<style type="text/css">
  .about-img{
    background: url("<%= asset_path('about1.jpg') %>") 0 20% no-repeat;
    -webkit-background-size: cover;
    background-size: cover;
  }
</style>

app/views/welcome/director.html.erb
<section class="inner-intro bg-img light-color overlay-before parallax-background">
  <div class="container">
    <div class="row title">
      <!--<h1 data-title="About"><span>Chairman's Message</span></h1>-->
    </div>
  </div>
</section>
<div id="about-section" class="padding pt-xs-60">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="heading-box pb-30">
          <h2><span>Principal's</span> Message</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="margin-right:15px; padding-left:0px">
          <div class=" wish-send haslayout">
            <figure>
              <%= image_tag('principal.jpg', style: "border:2px solid #26b1a4") %></figure>
          </div>
        </div>
        <% if @director_message.present? %>
          <p class="inner-p"><%= raw @director_message.description %></p>
        <% else %>
         <p class="inner-p">
          "Dear students and parents / Guardians of SDSK International Public SCHOOL.It is with great pleasure that I welcome you to our school website. I am honored and feel very privileged to be the Principal of SDSK International Public School, .On behalf of the entire team at AWS, I welcome you all to the SDSK family. It is extremely exciting to begin the academic year 2019-20."
          </p>
        <% end %>
        <p class="inr-hd"><b style="font-size:20px">MR. SHIVAM SINGH<br> DIRECTOR</b></p>
      </div>
      <div class="col-sm-3">
        <%= render 'layouts/side_bar' %>
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .mission-img{
    background: url("<%= asset_path('bg_1.jpg') %>") 0 20% no-repeat;
    -webkit-background-size: cover;
    background-size: cover;
  }
</style>